name: Create Salesforce Scratch Org (CumulusCI)

on:
  workflow_dispatch:
    inputs:
      org_type:
        description: 'Org Type (choose from orgs/ folder)'
        required: true
        default: 'dev'
        type: choice
        options:
          - beta
          - dev
          - feature
          - release
      days:
        description: 'Number of days before expiration (1-30)'
        required: true
        default: '7'
      org_name:
        description: 'Scratch Org Alias/Name'
        required: true
        default: 'cci_scratch_org'

jobs:
  create_scratch_org:
    runs-on: ubuntu-latest
    container: julian88tex/salesforce-cci-sfcli:latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate Dev Hub with Auth URL
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sfdx auth:sfdxurl:store -f auth-url.txt -a devhub
      - name: Install CumulusCI (workaround)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade 'cumulusci>=4.4.0'
      - name: Create Scratch Org
        env:
          ORG_TYPE: ${{ github.event.inputs.org_type }}
          DAYS: ${{ github.event.inputs.days }}
          ORG_NAME: ${{ github.event.inputs.org_name }}
        run: |
          cci org scratch "$ORG_NAME" "$ORG_TYPE" --days "$DAYS" --devhub devhub
      - name: Show Org Info
        env:
          ORG_NAME: ${{ github.event.inputs.org_name }}
        run: |
          cci org info "$ORG_NAME"

      - name: Clean up key file
        run: rm -f server.key 